//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1_variant_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class delivery_sashaEntities : DbContext
    {
        private static delivery_sashaEntities _context;
        public delivery_sashaEntities()
            : base("name=delivery_sashaEntities")
        {
        }
        public static delivery_sashaEntities GetContext()
        {
            if (_context == null)
                _context = new delivery_sashaEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
